import { redirect, notFound } from "next/navigation";
import Link from "next/link";
import { createClient } from "@/lib/supabase/server";
import { BottomNav } from "@/app/_components/bottom-nav";
import { todayInTimezone } from "@/lib/tasks/generator";
import { HeroRing } from "@/components/ui/hero-ring";
import { StatGrid } from "@/components/ui/stat-grid";
import { StatCard } from "@/components/ui/stat-card";
import { SectionHeader } from "@/components/ui/section-header";
import { RoutineRow } from "@/components/ui/routine-row";
import { DateToggle } from "@/components/ui/date-toggle";
import { addEntry, deleteEntry } from "../actions";

const KIND: Record<string, { label: string; emoji: string }> = {
  counter: { label: "Counter", emoji: "🔢" },
  streak: { label: "Streak", emoji: "🔥" },
  numeric: { label: "Numeric tracker", emoji: "📊" },
  calendar: { label: "Calendar", emoji: "📅" },
};

// Avoid using the generated PageProps<"/route"> helper here: it lives in
// .next/dev/types/routes.d.ts, which is not regenerated by `tsc --noEmit`
// alone (CI breaks). The explicit { params: Promise<...> } shape is part of
// the stable Next 16 contract.
export default async function CustomDetailPage(props: {
  params: Promise<{ id: string }>;
}) {
  const params = await props.params;
  const id = params.id;

  const supabase = await createClient();
  const {
    data: { user },
  } = await supabase.auth.getUser();
  if (!user) redirect("/login");

  const { data: profile } = await supabase
    .from("profiles")
    .select("timezone, onboarding_completed")
    .eq("id", user.id)
    .single();
  if (!profile?.onboarding_completed) redirect("/onboarding");

  const { data: mod } = await supabase
    .from("custom_modules")
    .select("id, name, kind, config, include_in_daily_tasks")
    .eq("id", id)
    .eq("user_id", user.id)
    .maybeSingle();
  if (!mod) notFound();

  const timezone = profile.timezone ?? "Europe/Rome";
  const today = todayInTimezone(timezone);

  const { data: entries } = await supabase
    .from("custom_module_entries")
    .select("id, date, value, label, completed, notes")
    .eq("custom_module_id", id)
    .eq("user_id", user.id)
    .order("date", { ascending: false })
    .limit(60);

  const config = (mod.config ?? {}) as { unit?: string; target?: number; daily_action?: string };

  // Stats by kind
  const totalCount = (entries ?? []).length;
  const totalValue = (entries ?? []).reduce((s, e) => s + Number(e.value ?? 0), 0);
  const streakDone = (entries ?? []).filter((e) => e.completed).length;
  const targetPct = config.target && config.target > 0
    ? Math.min(100, (totalValue / config.target) * 100)
    : null;

  const kindMeta = KIND[mod.kind] ?? { label: mod.kind, emoji: "✨" };

  return (
    <main className="mx-auto flex min-h-screen max-w-md flex-col px-5 pb-6 pt-7">
      <header className="flex items-start justify-between gap-3">
        <div className="flex items-center gap-3">
          <span aria-hidden="true" className="flex h-10 w-10 items-center justify-center rounded-full bg-surface text-lg">
            {kindMeta.emoji}
          </span>
          <div>
            <p className="text-sm text-text-secondary">{kindMeta.label}</p>
            <h1 className="text-2xl font-semibold tracking-tight">{mod.name}</h1>
          </div>
        </div>
        <Link
          href="/custom"
          className="rounded-md border border-border px-3 py-2 text-sm text-text-secondary hover:text-text-primary"
        >
          Indietro
        </Link>
      </header>

      {targetPct !== null ? (
        <section className="mt-7">
          <HeroRing
            value={Math.round(targetPct)}
            label="Progresso"
            subtitle={`${totalValue.toLocaleString("it-IT", { maximumFractionDigits: 2 })}${
              config.unit ? " " + config.unit : ""
            } / ${config.target}`}
            color={targetPct >= 80 ? "good" : targetPct >= 50 ? "warn" : "info"}
            size={220}
          />
        </section>
      ) : null}

      <section className={targetPct !== null ? "mt-7" : "mt-7"}>
        <StatGrid>
          {mod.kind === "counter" || mod.kind === "numeric" ? (
            <StatCard
              label={config.target ? "Totale" : "Totale entries"}
              value={totalValue.toLocaleString("it-IT", { maximumFractionDigits: 2 })}
              unit={config.unit}
              subtitle={config.target ? `target ${config.target}` : "in crescita"}
              status={
                config.target && targetPct !== null
                  ? targetPct >= 80
                    ? "good"
                    : targetPct >= 50
                      ? "warn"
                      : "neutral"
                  : "neutral"
              }
            />
          ) : null}
          {mod.kind === "streak" ? (
            <StatCard
              label="Giorni segnati"
              value={String(streakDone)}
              subtitle={`su ${totalCount} entries`}
              status={streakDone > 0 ? "good" : "neutral"}
            />
          ) : null}
          <StatCard
            label="Entries totali"
            value={String(totalCount)}
            subtitle={
              entries && entries[0]
                ? `ultima ${formatDate(entries[0].date)}`
                : "vuoto"
            }
          />
        </StatGrid>
      </section>

      <section className="mt-7 rounded-xl border border-border bg-surface p-5">
        <SectionHeader label="Aggiungi entry" />
        <form action={addEntry} className="mt-3 space-y-2">
          <input type="hidden" name="custom_module_id" value={mod.id} />
          <DateToggle name="date" defaultDate={today} />
          {/* Render del flex container SOLO quando uno dei kind
              che produce un child è attivo. Closes ECC end-of-
              sprint U3 a11y M1 — calendar kind lasciava un
              <div className="flex gap-2"> vuoto. */}
          {mod.kind === "counter" || mod.kind === "numeric" || mod.kind === "streak" ? (
            <div className="flex gap-2">
              {mod.kind === "counter" || mod.kind === "numeric" ? (
                <input
                  type="number"
                  name="value"
                  step="0.01"
                  aria-label={`Valore${config.unit ? " (" + config.unit + ")" : ""}`}
                  placeholder={`valore${config.unit ? " (" + config.unit + ")" : ""}`}
                  className="flex-1 rounded-md border border-border bg-bg px-2 py-2 text-sm text-text-primary placeholder:text-text-muted focus:border-accent-info focus:outline-none"
                />
              ) : null}
              {mod.kind === "streak" ? (
                <label className="flex flex-1 items-center justify-center gap-2 rounded-md border border-border bg-bg px-2 py-2 text-sm text-text-secondary">
                  <input type="checkbox" name="completed" value="true" defaultChecked className="accent-accent-good" />
                  <span>Fatto oggi</span>
                </label>
              ) : null}
            </div>
          ) : null}
          {mod.kind === "calendar" ? (
            <input
              type="text"
              name="label"
              maxLength={120}
              aria-label="Evento"
              placeholder="evento (es. esame microeconomia)"
              className="w-full rounded-md border border-border bg-bg px-2 py-2 text-sm text-text-primary placeholder:text-text-muted focus:border-accent-info focus:outline-none"
            />
          ) : null}
          <input
            type="text"
            name="notes"
            maxLength={200}
            aria-label="Note entry"
            placeholder="note (opzionale)"
            className="w-full rounded-md border border-border bg-bg px-2 py-2 text-sm text-text-primary placeholder:text-text-muted focus:border-accent-info focus:outline-none"
          />
          <button
            type="submit"
            className="w-full rounded-md bg-text-primary px-4 py-2.5 text-sm font-medium text-bg transition-opacity hover:opacity-90"
          >
            + entry
          </button>
        </form>
      </section>

      {entries && entries.length > 0 ? (
        <section className="mt-7">
          <SectionHeader label="Ultime entries" meta={`${entries.length} mostrate`} />
          <ul className="mt-2 divide-y divide-border rounded-xl border border-border bg-surface px-4">
            {entries.map((e) => (
              <li key={e.id}>
                <RoutineRow
                  emoji={e.completed ? "✅" : kindMeta.emoji}
                  text={
                    <span>
                      <span className="font-medium">{formatDate(e.date)}</span>
                      {e.value !== null && e.value !== undefined ? (
                        <span className="ml-2 tabular-nums text-text-secondary">
                          {Number(e.value).toLocaleString("it-IT", { maximumFractionDigits: 2 })}
                          {config.unit ? ` ${config.unit}` : ""}
                        </span>
                      ) : null}
                      {e.label ? (
                        <span className="ml-2 text-xs text-text-muted">{e.label}</span>
                      ) : null}
                      {e.notes ? (
                        <span className="mt-0.5 block text-xs text-text-secondary">
                          {e.notes}
                        </span>
                      ) : null}
                    </span>
                  }
                  trailing={
                    <form action={deleteEntry}>
                      <input type="hidden" name="id" value={e.id} />
                      <input type="hidden" name="custom_module_id" value={mod.id} />
                      <button
                        type="submit"
                        aria-label="Elimina"
                        className="inline-flex h-9 w-9 items-center justify-center rounded-md text-text-muted hover:text-accent-bad"
                      >
                        ×
                      </button>
                    </form>
                  }
                />
              </li>
            ))}
          </ul>
        </section>
      ) : null}

      <div className="h-16" aria-hidden="true" />
      <BottomNav active="Custom" />
    </main>
  );
}

function formatDate(iso: string): string {
  const d = new Date(iso + "T00:00:00");
  return d.toLocaleDateString("it-IT", { day: "numeric", month: "short" });
}
